### ISSUE TITLE
dataset can not found

### ISSUE THREAD

**Issue by haoyankai** [atrey-a/T3AAS-v1-benchmarking#1]
i fillout the form and didn't receive the valid dataset url or password, could you please share the dataset, thank you

**Comment by atrey-a** [comment]
Thank you for reaching out! I have shared the dataset URL and password via the email address you provided when filling out the form. Please check your inbox (and spam/junk folder) for an email from us. If you still haven’t received it or if there's been an issue with the email, feel free to let me know, and I'll assist you further.

Best regards,
Saurabh

**Comment by haoyankai** [comment]
Thank you so much, I have received the dataset and opened it, thank you for sharing
